// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mykltfxafrlaudhmrknk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15a2x0ZnhhZnJsYXVkaG1ya25rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjkzODUsImV4cCI6MjA2NDU0NTM4NX0.eynnW6_tex95ZpqjAHf2xJWBh9qgWea2asjEUgSyoA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);